deveLOOPers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "welcome#index"

  get 'welcome/index'

  resources :articles do
    resources :comments, only: [:create, :destroy] do
      member do
        put 'approve'
        delete 'reject'
      end
    end

    member do
      post 'add_vote'
      post 'remove_vote'
    end

    collection do
      get 'search'
    end
  end
  
  namespace :api do
    resources :articles, only: [:index, :show]
  end

  
  get '/users/:nickname', to: 'users#show', as: 'user_profile'
  get '/users/:nickname/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/users/:nickname', to: 'users#update'
end

deveLOOPers/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    has_rich_text :content
  
    scope :published, -> { where(published: true) }

    belongs_to :user
    has_many :comments, dependent: :destroy
    has_and_belongs_to_many :tags

    accepts_nested_attributes_for :tags

    

    def self.search(query)
        if query.present?
          if query.start_with?('tag:')
            tag_name = query.split(':')[1]
            joins(:tags).where(tags: { name: tag_name }).published
          else
            where("title LIKE ? OR content LIKE ?", "%#{query}%", "%#{query}%").published
          end
        else
          published
        end
      end
    
      private
    
end

deveLOOPers/app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
    before_action :set_article, only: [:show]

    # GET /api/articles
    def index
      @articles = Article.published
      render json: @articles, each_serializer: ArticleSerializer
    end

    # GET /api/articles/:id
    def show
      render json: @article, serializer: ArticleSerializer
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end
end

deveLOOPers/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy, :add_vote, :remove_vote]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.search(params[:query])
  end

  def show
    @article = Article.find(params[:id])
  @comment = Comment.new 

  @approved_comments = @article.comments.approved

  @user_comments = @article.comments.where(user: current_user).or(@article.comments.pending)

  @comment_list = @approved_comments + @user_comments

  @pending_comments = @article.comments.pending.where(user: @article.user)

  if current_user == @article.user
    @pending_comments = @article.comments.pending
  end
  end

  def new
    @article = current_user.articles.build
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    tag_ids = params[:article][:tag_ids].present? ? params[:article][:tag_ids].reject(&:blank?) : []

    if params[:article][:new_tags].present?
      new_tag_names = params[:article][:new_tags].split(",").map(&:strip)
      new_tag_names.each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name)
        tag_ids << tag.id
      end
    end

    @article.tag_ids = tag_ids


    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  def add_vote
    @article.vote_count += 1
    @article.save

    redirect_to @article
  end

  def remove_vote
    @article.vote_count -= 1
    @article.save

    redirect_to @article
  end

  def search
    @query = params[:query]
    @articles = if @query.present?
                  if @query.start_with?('tag:')
                    tag_name = @query.split(':').last
                    Article.joins(:tags).where(tags: { name: tag_name }).distinct
                  else
                    Article.published.where('title LIKE ? OR content LIKE ?', "%#{@query}%", "%#{@query}%")
                  end
                else
                  Article.published
                end
    render :index
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :published, tag_ids: [])
  end

  def authorize_user
    unless @article.user == current_user
      redirect_to @article, alert: "You are not authorized to perform this action."
    end
  end
end

deveLOOPers/app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

deveLOOPers/app/helpers/articles_helper.rb
module ArticlesHelper
end

deveLOOPers/app/views/articles/_article.html.erb
<div id="<%= dom_id(article) %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.title') %>:</strong>
    <%= article.title %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.content') %>:</strong>
    <%= article.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.is_published') %>:</strong>
    <%= article.published %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.vote_count') %>:</strong>
    <%= article.vote_count %>
    
    <%= button_to t('articles.add_vote'), add_vote_article_path(article), method: :post, class: "rounded-lg py-3 px-5 bg-green-600 text-white block mr-5" %>
    <% unless article.vote_count.zero? %>
      <%= button_to t('articles.remove_vote'), remove_vote_article_path(article), method: :post, class: "rounded-lg py-3 px-5 bg-red-600 text-white block" %>
    <% end %>  
    
  </p>
</div>

deveLOOPers/app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, t('articles.error')) %> <%= t('articles.prohibited') %>:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, t('articles.title') %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, t('articles.content') %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :published, t('articles.published') %>
    <%= form.check_box :published %>
  </div>

  <div class="field">
    <%= form.label :tags, t('articles.tags') %><br>
    <%# Checkboxes for existing tags %>
    <% Tag.all.each do |tag| %>
      <%= form.check_box :tag_ids, { multiple: true }, tag.id, nil %>
      <%= tag.name %><br>
    <% end %>
    <%# Text field for creating new tags %>
    <%= form.text_field :new_tags, placeholder: t('articles.new_tags_placeholder') %>
  </div>

  <div class="actions">
    <%= form.submit t('articles.create_article'), class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
  </div>
<% end %>

deveLOOPers/app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('articles.editing_article') %></h1>

  <%= render "form", article: @article %>

  <%= link_to t('articles.show_this_article'), @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to t('articles.back_to_articles'), articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

deveLOOPers/app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, t('articles.title') %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-blue-800"><%= t('articles.title') %> <%= @articles.count %></h1>
    <% if user_signed_in? %>
      <a href="<%= new_article_path %>" class="rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"><%= t('articles.add_new_article') %></a>
    <% end %>
  </div>

  <%= form_with url: search_articles_path, method: :get, local: true do %>
    <div class="field">
      <%= label_tag :query, t('articles.search_placeholder') %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag t('articles.search_button'), class: 'btn btn-primary' %>
    </div>
  <% end %>

  <div class="articles-list flex flex-wrap">
    <% @articles.each_with_index do |article, index| %>
      <div class="article-card w-full sm:w-1/2 md:w-1/3 lg:w-1/4 p-4 border border-gray-300 rounded-lg box-border mb-4">
        <b class="text-blue-600"><%= t('articles.article') %> <%= index + 1 %></b>
        <div>
          <h2 class="font-bold text-xl"><%= link_to article.title, article %></h2>
          <p><%= article.content.to_plain_text.truncate(100) %></p>
          <p class="my-5">
            <strong class="block font-extralight mb-1"><%= t('articles.created_at') %> <%= article.created_at.strftime("%Y-%m-%d | %A") %></strong>
          </p>
          <a href="<%= article_path(article) %>" class="ml-2 rounded-lg py-3 px-5 bg-blue-300 inline-block font-medium"><%= t('articles.show_this_article') %></a>
        </div>
      </div>
    <% end %>
  </div>
</div>

deveLOOPers/app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('articles.new_article') %></h1>

  <%= render "form", article: @article %>

  <%= link_to t('articles.back_to_articles'), articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
</div>

deveLOOPers/app/views/articles/show.html.erb
<div id="<%= dom_id @article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.title') %>:</strong>
    <%= @article.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.publisher') %>:</strong>
    <%= @article.user.nickname %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.content') %>:</strong>
    <%= @article.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.is_published') %>:</strong>
    <%= @article.published %>
  </p>

  <div>
    <h2 class="font-bold text-2xl"><%= t('articles.tags') %></h2>
    <% @article.tags.each do |tag| %>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#<%= tag.name %></span>
    <% end %>
  </div>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('articles.vote_count') %>:</strong>
    <%= @article.vote_count %>

    <%= button_to t('articles.add_vote'), add_vote_article_path(@article), method: :post, class: "rounded-lg py-3 px-5 bg-green-600 text-white block mr-5" %>
    <% unless @article.vote_count.zero? %>
      <%= button_to t('articles.remove_vote'), remove_vote_article_path(@article), method: :post, class: "rounded-lg py-3 px-5 bg-red-600 text-white block" %>
    <% end %>
  </p>

  <div class="inline-block ml-2">
    <% if @article.user == current_user %>
      <%= link_to t('articles.edit'), edit_article_path(@article), class: "ml-2 rounded-lg py-3 px-5 bg-yellow-600 text-white inline-block font-medium" %>
      <%= button_to t('articles.destroy'), @article, method: :delete, class: "bg-red-200 text-red-500 mt-2 rounded-lg py-3 px-5 font-medium" %>
    <% end %>
  </div>

  <hr>

  <div>
    <h2 class="font-bold text-2xl"><%= t('articles.comments') %> (<%= @article.comments.approved.count %>)</h2>
    <% @article.comments.each do |comment| %>
      <% if comment.user == current_user || current_user == @article.user || comment.state == "approved" %>
        <div class="mt-5 max-w-sm p-3 bg-white border border-gray-200 rounded-lg shadow relative">
          <div class="absolute top-0 right-0 p-2 bg-gray-100 rounded-bl-lg text-sm font-semibold text-gray-700">
            <%= comment.state.capitalize %>
          </div>
          <p class="my-5">
            <strong class="block font-medium mb-1"><%= t('articles.commenter') %>:</strong>
            <%= comment.user.nickname %>
          </p>
          <p class="my-5">
            <strong class="block font-medium mb-1"><%= t('articles.body') %>:</strong>
            <%= comment.body %>
          </p>
        </div>
      <% end %>
    <% end %>
      <% if user_signed_in? %>
        <%= form_with(model: [ @article, @comment ], class: "mt-5") do |form| %>
         <%= form.hidden_field :commenter, value: current_user&.nickname %>
          <p>
           <%= form.label :body %><br>
           <%= form.text_area :body, rows: 4 %>
          </p>
          <p>
           <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
          </p>
      <% end %>
    <% end %>
  </div>
</div>