deveLOOPers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "welcome#index"

  get 'welcome/index'

  resources :articles do
    resources :comments, only: [:create, :destroy] do
      member do
        put 'approve'
        delete 'reject'
      end
    end

    member do
      post 'add_vote'
      post 'remove_vote'
    end

    collection do
      get 'search'
    end
  end
  
  namespace :api do
    resources :articles, only: [:index, :show]
  end

  
  get '/users/:nickname', to: 'users#show', as: 'user_profile'
  get '/users/:nickname/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/users/:nickname', to: 'users#update'
end

deveLOOPers/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @articles = Article.where(published: true)
        @user = User.find_by_id(params[:id])
    end
end

deveLOOPers/app/helpers/welcome_helper.rb
module WelcomeHelper
end

deveLOOPers/app/views/welcome/index.html.erb
<div class="flex justify-center">
  <div class="flex flex-col mx-auto items-center text-center">
    <h1 class="font-bold text-4xl mt-10"><%= t('welcome') %></h1>
    <p class="mt-5 text-lg"><%= t('see_articles', count: @articles.count) %> <%= link_to t('here'), articles_path, class: "text-sky-400 underline" %></p>

    <% if user_signed_in? %>
      <div class="mt-10 text-center">
        <%= link_to t('add_new_article'), new_article_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
      </div>
      <div class="text-center mt-5">
        <%= link_to t('my_profile'), user_profile_path(current_user.nickname), class: "btn btn-primary inline-block rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      </div>
    <% end %>
  </div>

  <div class="mt-10 ml-10">
    <h2 class="font-bold text-2xl"><%= t('published_articles') %></h2>
    <ul class="mt-5 space-y-2">
      <% @articles.each do |article| %>
        <li class="border-b border-gray-200 pb-3">
          <h3 class="text-xl font-semibold mb-2"><%= link_to article.title, article_path(article), class: "text-blue-600 underline" %></h3>
          <div>
            <% article.tags.each do |tag| %>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#<%= tag.name %></span>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>