deveLOOPers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "welcome#index"

  get 'welcome/index'

  resources :articles do
    resources :comments, only: [:create, :destroy] do
      member do
        put 'approve'
        delete 'reject'
      end
    end

    member do
      post 'add_vote'
      post 'remove_vote'
    end

    collection do
      get 'search'
    end
  end
  
  namespace :api do
    resources :articles, only: [:index, :show]
  end

  
  get '/users/:nickname', to: 'users#show', as: 'user_profile'
  get '/users/:nickname/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/users/:nickname', to: 'users#update'
end

deveLOOPers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeveLooPers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      body {
        background-color: #f3f4f6; 
      }
    </style>
  </head>

  <body class="font-sans leading-normal tracking-normal">
  <nav class="bg-red-800 p-4 shadow-md">
    <div class="container mx-auto flex items-center justify-between">
      <a href="/" class="text-white text-2xl font-semibold">DeveL∞Pers</a>
      <div class="flex items-center space-x-4">
        <% if user_signed_in? %>
          <span class="text-white"><%= t('logged_in_as') %> <strong><%= current_user.email %></strong></span>
          <%= link_to t('profile.edit_profile'), edit_user_profile_path(current_user.nickname), class: "text-white hover:bg-red-700 px-3 py-2 rounded" %>
          <%= link_to t('logout'), destroy_user_session_path, data: { turbo_method: :delete }, class: "text-white hover:bg-red-700 px-3 py-2 rounded" %>
        <% else %>
         <form class="button_to" method="post" action="/users/auth/github?locale=en">
            <button data-turbo="false" type="submit" class="text-white hover:bg-red-700 px-3 py-2 rounded">
              <%= t('sign_in_with_github') %>
            </button>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" autocomplete="off">
         </form>
        <% end %>
      </div>
      <div class="text-white space-x-2">
        <%= link_to 'TR', url_for(locale: 'tr'), class: "hover:underline" %> | 
        <%= link_to 'EN', url_for(locale: 'en'), class: "hover:underline" %>
      </div>
    </div>
  </nav>

  <main class="container mx-auto mt-10 px-5">
    <%= yield %>
  </main>
</body>
</html>