deveLOOPers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "welcome#index"

  get 'welcome/index'

  resources :articles do
    resources :comments, only: [:create, :destroy] do
      member do
        put 'approve'
        delete 'reject'
      end
    end

    member do
      post 'add_vote'
      post 'remove_vote'
    end

    collection do
      get 'search'
    end
  end
  
  namespace :api do
    resources :articles, only: [:index, :show]
  end

  
  get '/users/:nickname', to: 'users#show', as: 'user_profile'
  get '/users/:nickname/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/users/:nickname', to: 'users#update'
end

deveLOOPers/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  before_validation :set_nickname, on: :create

  validates :nickname, presence: true, uniqueness: true

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
  
    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20],
        nickname: data['nickname'] || data['email'].split('@').first.gsub('.', '')
      )
    end
    user
  end

  private

  def set_nickname
    self.nickname = email.split('@').first if nickname.blank?
  end
end

deveLOOPers/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

deveLOOPers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def show
    if @user
      @pending_comments = Comment.joins(article: :user).where(users: { id: @user.id }, comments: { state: 'pending' })
      @published_articles = @user.articles.published
      @articles = @user.articles
    else
      redirect_to root_path, alert: "User not found"
    end
  end

  def edit
    authorize_user
  end

  def update
    authorize_user
    if @user.update(user_params)
      redirect_to user_profile_path(@user), notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(:nickname)
  end

  def authorize_user
    unless current_user == @user
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end

deveLOOPers/app/views/users/edit.html.erb
<h1 class="font-bold text-4xl"><%= t('edit_profile.title') %></h1>

<%= form_with(model: @user, url: user_profile_path(@user), method: :patch) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, t('edit_profile.error')) %> <%= t('edit_profile.prohibited') %></h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('edit_profile.nickname') %>
    <%= form.text_field :nickname %>
  </div>

  <div class="actions">
    <%= form.submit t('edit_profile.update_profile'), class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to t('edit_profile.back_to_profile'), user_profile_path(@user), class: "btn btn-secondary" %>

deveLOOPers/app/views/users/show.html.erb
<div class="mt-10">
  <h1 class="text-3xl font-bold mb-4"><%= @user.nickname %> <%= t('profile.title') %></h1>
  <p class="text-lg mb-6"><%= t('profile.email') %>: <%= @user.email %></p>

  

  <h2 class="text-2xl font-semibold mb-4"><%= t('profile.published_articles') %></h2>
  <ul class="mt-5 space-y-2">
    <% @published_articles.each do |article| %>
      <li class="border-b border-gray-200 pb-3">
        <h3 class="text-xl font-semibold mb-2"><%= link_to article.title, article_path(article), class: "text-blue-600 underline" %></h3>
        <div>
          <% article.tags.each do |tag| %>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#<%= tag.name %></span>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <h2 class="text-2xl font-semibold mb-4"><%= t('profile.pending_comments') %></h2>
  <% @pending_comments.each do |comment| %>
    <div class="bg-white shadow-md rounded-lg p-4 mb-4">
      <p class="text-gray-700 mb-2"><%= comment.body %></p>
      <p class="text-gray-500 mb-4">
        <%= t('profile.article') %>: 
        <%= link_to comment.article.title, article_path(comment.article), class: "text-blue-500 hover:underline" %>
      </p>
      <div class="flex space-x-2">
        <%= link_to t('profile.approve'), approve_article_comment_path(comment.article, comment), method: :put, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded", data: { turbo_method: :put } %>
        <%= link_to t('profile.reject'), reject_article_comment_path(comment.article, comment), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded", data: { turbo_method: :delete } %>
      </div>
    </div>
  <% end %>
</div>